data_path: "../Data/d1carter_data_w_gaps.csv"
parameters_path: "../Results/1000_sample_biolum_3_wk.csv"
target: "Lingulodinium_polyedra"
bloom_thresh: 5.977
samp: 5
n: 750
p: 0.2
forecast_type: lstm
data_bank_sz: 250
train_sz: 400
seq_len: 10
noisy_prop: 0.5
noise_pct: 0.03
batch_sz: 16
tcn_channel: 64
atn_hds: 4
lstm_hd_sz: 16
lstm_num_lyrs: 2
dropout: 0.5
bloom_pen: 1.5
learning_rate: 0.00001
save_path: "../Results/Lingulodinium_LSTM.pth"